import type { Metadata } from "next";
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import QueryProvider from "../layout/query-provider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next.js Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <NuqsAdapter>
          <QueryProvider>
            {children}
          </QueryProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
