import type { Metadata } from "next";
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import QueryProvider from "@/layout/query-provider";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import "./globals.css";

export const metadata: Metadata = {
  title: "17hz studio",
  description: "Generated by 17hz studio",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <NextThemesProvider attribute={'class'}>
          <NuqsAdapter>
            <QueryProvider>
              {children}
            </QueryProvider>
          </NuqsAdapter>
        </NextThemesProvider>
      </body>
    </html>
  );
}
